# Generated by Django 3.1.7 on 2021-03-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20210316_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=500)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=111)),
                ('zip', models.IntegerField(default='')),
            ],
        ),
    ]
