# Generated by Django 3.1.7 on 2021-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_updateorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=111),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.CharField(default='', max_length=111),
        ),
    ]
