# Generated by Django 3.1.7 on 2021-04-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20210324_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
